import {afterEach,beforeEach,expect,test,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import FacilitiesPage from '../FacilitiesPage';
afterEach(()=>{cleanup();vi.unstubAllGlobals();sessionStorage.clear();});
const claim={_id:'claim',gymName:'Test Gym',workEmail:'owner@example.test',status:'pending_review',paymentStatus:'paid',paymentExpiresAt:'2099-01-01',ownershipVerifiedAt:'2026-01-01',provisioningState:'failed'};
let calls:any[]=[];
function server(item:any=claim,denied=false){vi.stubGlobal('fetch',vi.fn(async(url:string,options:any)=>{calls.push([url,options]);return {ok:!denied,json:async()=>denied?{message:'Unauthorized'}:{success:true,data:{items:[item]}}};}));}
beforeEach(()=>{calls=[];sessionStorage.setItem('p2p_backend_jwt','p2p-only-token');sessionStorage.setItem('p2p_admin_token','wrong-sql-token');});
test('pending applications use P2P token and verified payment gates approval',async()=>{server({...claim,paymentStatus:'pending'});render(<FacilitiesPage/>);await screen.findByText('Test Gym');expect((screen.getByText('Retry provisioning') as HTMLButtonElement).disabled).toBe(true);expect(calls[0][1].headers.Authorization).toBe('Bearer p2p-only-token');});
test('retry calls real approval endpoint and reloads',async()=>{server();render(<FacilitiesPage/>);await screen.findByText('Test Gym');fireEvent.click(screen.getByText('Retry provisioning'));await waitFor(()=>expect(calls.some(([url,options])=>url.endsWith('/claim/approve')&&options.method==='POST')).toBe(true));});
test('rejection requires an explicit reason',async()=>{server();render(<FacilitiesPage/>);await screen.findByText('Test Gym');expect((screen.getByText('Reject') as HTMLButtonElement).disabled).toBe(true);fireEvent.change(screen.getByLabelText('Decision reason'),{target:{value:'Ownership documents do not match'}});fireEvent.click(screen.getByText('Reject'));await waitFor(()=>expect(calls.some(([url,options])=>url.endsWith('/reject')&&JSON.parse(options.body).reason==='Ownership documents do not match')).toBe(true));});
test('denied requests expose error without fake facility metrics',async()=>{server(claim,true);render(<FacilitiesPage/>);await screen.findByRole('alert');expect(screen.queryByText('Test Gym')).toBeNull();expect(screen.queryByText('$450K ARR')).toBeNull();});
test('SQL founder token alone cannot access P2P claims',async()=>{server();sessionStorage.removeItem('p2p_backend_jwt');render(<FacilitiesPage/>);await screen.findByRole('alert');expect(calls).toHaveLength(0);});
test('ownership review sends the verified owner and explicit evidence',async()=>{server({...claim,ownershipVerifiedAt:null});render(<FacilitiesPage/>);await screen.findByText('Test Gym');fireEvent.change(screen.getByLabelText('Verified owner user ID'),{target:{value:'owner-user'}});fireEvent.change(screen.getByLabelText('Ownership review evidence'),{target:{value:'Reviewed ownership documents'}});fireEvent.click(screen.getByText('Verify ownership'));await waitFor(()=>expect(calls.some(([url,options])=>url.endsWith('/verify-ownership')&&JSON.parse(options.body).ownerUserId==='owner-user')).toBe(true));});
test('branding review and override use the tenant endpoint',async()=>{vi.stubGlobal('fetch',vi.fn(async(url:string,options:any)=>{calls.push([url,options]);return {ok:true,json:async()=>({success:true,data:url.endsWith('/branding')?{gymName:'Test Gym',logoUrl:'https://example.test/logo.png',primaryColor:'#112233',secondaryColor:'#223344',accentColor:'#334455'}:{items:[{...claim,status:'approved',tenantId:'tenant-a'}]}})};}));render(<FacilitiesPage/>);await screen.findByText('Test Gym');fireEvent.click(screen.getByText('Review branding'));await screen.findByText('Save branding override');fireEvent.change(screen.getByLabelText('gymName'),{target:{value:'Updated Gym'}});fireEvent.click(screen.getByText('Save branding override'));await waitFor(()=>expect(calls.some(([url,options])=>url.endsWith('/tenants/tenant-a/branding')&&options.method==='PUT'&&JSON.parse(options.body).gymName==='Updated Gym')).toBe(true));});
