import mongoose, {Schema} from 'mongoose';
const membership = new Schema({tenantId:{type:String,required:true},userId:{type:Schema.Types.ObjectId,required:true},role:{type:String,enum:['owner','admin','staff','trainer','member'],required:true},status:{type:String,enum:['active','revoked'],default:'active'},updatedBy:Schema.Types.ObjectId},{timestamps:true});
membership.index({tenantId:1,userId:1},{unique:true});
const branding = new Schema({tenantId:{type:String,required:true,unique:true},gymName:{type:String,required:true},logoUrl:{type:String,default:''},primaryColor:{type:String,default:'#B83B12'},secondaryColor:{type:String,default:'#202020'},accentColor:{type:String,default:'#B83B12'},brandingStatus:{type:String,enum:['default','configured'],default:'default'},updatedBy:Schema.Types.ObjectId},{timestamps:true});
const selection = new Schema({userId:{type:Schema.Types.ObjectId,required:true,unique:true},tenantId:{type:String,default:null}});
const audit = new Schema({tenantId:String,applicationId:Schema.Types.ObjectId,actorId:Schema.Types.ObjectId,action:String,reason:String},{timestamps:true});
export const TenantMembership=mongoose.models.TenantMembership||mongoose.model('TenantMembership',membership);
export const TenantBranding=mongoose.models.TenantBranding||mongoose.model('TenantBranding',branding);
export const TenantSelection=mongoose.models.TenantSelection||mongoose.model('TenantSelection',selection);
export const TenantAudit=mongoose.models.TenantAudit||mongoose.model('TenantAudit',audit);
