/** Default approved starter block seeded for every built-in trainer. */
export const BUILT_IN_STARTER_BLOCK = {
  name: "Starter Full Body",
  description: "Default approved exercises for built-in trainers",
  category: "full_body" as const,
  exercises: [
    {
      name: "Goblet Squat",
      muscleGroup: "legs" as const,
      difficulty: "beginner" as const,
      equipment: "dumbbell or kettlebell",
      sets: 3,
      reps: "10-12",
      restTime: "60s",
      rpe: "7",
      tags: ["compound", "lower_body"],
    },
    {
      name: "Push-Up",
      muscleGroup: "chest" as const,
      difficulty: "beginner" as const,
      equipment: "bodyweight",
      sets: 3,
      reps: "8-15",
      restTime: "45s",
      rpe: "7",
      tags: ["compound", "upper_body"],
    },
    {
      name: "Dumbbell Row",
      muscleGroup: "back" as const,
      difficulty: "intermediate" as const,
      equipment: "dumbbells",
      sets: 3,
      reps: "10-12",
      restTime: "60s",
      rpe: "7-8",
      tags: ["compound", "pull"],
    },
    {
      name: "Romanian Deadlift",
      muscleGroup: "glutes" as const,
      difficulty: "intermediate" as const,
      equipment: "dumbbells or barbell",
      sets: 3,
      reps: "8-10",
      restTime: "90s",
      rpe: "7-8",
      tags: ["hinge", "posterior_chain"],
    },
    {
      name: "Plank",
      muscleGroup: "core" as const,
      difficulty: "beginner" as const,
      equipment: "bodyweight",
      sets: 3,
      reps: "30-45 seconds",
      restTime: "45s",
      rpe: "6-7",
      tags: ["core", "stability"],
    },
    {
      name: "Walking Lunges",
      muscleGroup: "legs" as const,
      difficulty: "intermediate" as const,
      equipment: "bodyweight or dumbbells",
      sets: 3,
      reps: "10 each leg",
      restTime: "60s",
      rpe: "7",
      tags: ["unilateral", "legs"],
    },
  ],
};
