// Firebase options stubbed — Firebase not yet configured (Task #37).
    // This file will be regenerated by FlutterFire CLI when Firebase is added.
    class DefaultFirebaseOptions {
    // Populated when GoogleService-Info.plist is present and Firebase is configured.
    }
    