name: pler_to_pler_app
description: "A new Flutter project."

publish_to: 'none'

version: 2.0.1+74

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  url_launcher: ^6.3.2
  intl: ^0.20.2
  logger: ^2.6.2
  dotted_border: ^3.1.0
  file_picker: ^10.3.10
  flutter_screenutil: ^5.9.3
  pinput: ^6.0.1
  http: ^1.6.0
  video_player: ^2.9.2
  mime_type: ^1.0.1
  shimmer: ^3.0.0
  shared_preferences: ^2.5.4
  socket_io_client: ^3.1.4
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.2
  chat_bubbles: ^1.8.0
  flutter_svg: ^2.2.3
  confetti: ^0.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.9.0
  health: ^13.1.1
  in_app_purchase: ^3.2.0
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.14.4

flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
    lottie: true


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/


  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-Regular.ttf
