export const sanitizeOptions = {
    allowedTags: [
      "b",
      "i",
      "em",
      "strong",
      "a",
      "p",
      "br",
      "ul",
      "ol",
      "li",
      "blockquote",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "code",
      "pre",
      "img",
      "u",
    ],
    allowedAttributes: {
      a: ["href", "target", "style"],
      img: ["src", "alt", "style"],
      p: ["style"],
      b: ["style"],
      i: ["style"],
      em: ["style"],
      strong: ["style"],
      ul: ["style"],
      ol: ["style"],
      li: ["style"],
      blockquote: ["style"],
      h1: ["style"],
      h2: ["style"],
      h3: ["style"],
      h4: ["style"],
      h5: ["style"],
      h6: ["style"],
      code: ["style"],
      pre: ["style"],
      span: ["style"],
      u: ["style"],
    },
    allowedIframeHostnames: ["www.youtube.com"],
  };