

import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:pler_to_pler_app/features/home/user_home_screen.dart';
import 'package:pler_to_pler_app/features/nav_bar/presentation/screens/nav_bar.dart';
import 'package:pler_to_pler_app/routes/app_routes.dart';
import 'package:pler_to_pler_app/widgets/custom_button2.dart';

import '../../../../../widgets/custom_app_bar.dart';
import '../../../../../widgets/custom_button.dart';
import '../../../../../widgets/custom_container.dart';
import '../../../../../widgets/custom_network_image.dart';
import '../../../../../widgets/custom_scaffold.dart';
import '../../../../../widgets/custom_text.dart';
import '../../../../../widgets/custom_text_field.dart';
import '../widgets/add_exercise_block.dart';

class CreateExercisePlanScreen extends StatefulWidget {
  const CreateExercisePlanScreen({super.key});

  @override
  State<CreateExercisePlanScreen> createState() => _CreateExercisePlanScreenState();
}

class _CreateExercisePlanScreenState extends State<CreateExercisePlanScreen> {
  // Navigation & Process States
  bool _isSecondPart = false;
  bool _isLoading = false;
  bool _isAutoGenerated = false;

  String selectedType = "Manual";
  String? selectedDuration = "1 Week";
  String? selectedLevel = "Beginner";
  int selectedDay = 1;
  final TextEditingController _nameController = TextEditingController();

  final Map<String, int> durationToDays = {
    "1 Week": 7,
    "2 Weeks": 14,
    "30 Days": 30,
  };

  @override
  Widget build(BuildContext context) {
    // 1. Show Loading Screen during Auto-generation
    if (_isLoading) return _buildLoadingScreen();

    return CustomScaffold(
      appBar: CustomAppBar(
        title: (_isSecondPart || _isAutoGenerated) ? 'Exercise days' : 'Create exercise plan',
        backAction: () {
          if (_isAutoGenerated) {
            setState(() => _isAutoGenerated = false);
          } else if (_isSecondPart) {
            setState(() => _isSecondPart = false);
          } else {
            Get.back();
          }
        },
      ),
      // 2. Body switches between Part 1, Part 2 (Manual), or Auto Generated Result
      body: _isAutoGenerated
          ? _buildAutoGeneratedPart()
          : (_isSecondPart ? _buildPartTwo() : _buildPartOne()),
    );
  }

  // --- LOADING SCREEN (Auto Generate) ---
  Widget _buildLoadingScreen() {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: EdgeInsets.all(24.r),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomText(
                text: "Generating personalized\nexercise for Johnson",
                fontSize: 22.sp,
                fontWeight: FontWeight.bold,
                textAlign: TextAlign.center,
              ),
              SizedBox(height: 12.h),
              CustomText(
                text: "Processing all data from johnson’s profile to build personalized exercise",
                color: Colors.grey,
                textAlign: TextAlign.center,
              ),
              SizedBox(height: 60.h),
              SizedBox(
                width: 100.w,
                height: 100.w,
                child: CircularProgressIndicator(
                  strokeWidth: 8.w,
                  color: Colors.orange,
                  backgroundColor: Colors.orange.withOpacity(0.1),
                ),
              ),
              SizedBox(height: 40.h),
              CustomText(text: "Might take 1~2 minutes", color: Colors.grey),
            ],
          ),
        ),
      ),
    );
  }

  // --- PART 1: Plan Details ---
  Widget _buildPartOne() {
    bool isAuto = selectedType == "Auto generate";

    return SingleChildScrollView(
      padding: EdgeInsets.all(16.r),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildSwitcher(),
          SizedBox(height: 24.h),

          if (isAuto) ...[
            CustomContainer(
              paddingAll: 12.r,
              radiusAll: 16.r,
              color: Colors.white,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  CustomText(text: "Assigned Client", fontWeight: FontWeight.bold),
                  CustomContainer(
                    paddingHorizontal: 12.w,
                    paddingVertical: 6.h,
                    radiusAll: 12.r,
                    color: Colors.black.withOpacity(0.05),
                    child: Row(
                      children: [
                        CustomNetworkImage(
                          imageUrl: "https://picsum.photos/100",
                          width: 24.w,
                          height: 24.w,
                          boxShape: BoxShape.circle,
                        ),
                        SizedBox(width: 8.w),
                        CustomText(text: "Johnson jr", fontSize: 13.sp),
                      ],
                    ),
                  ),
                ],
              ),
            ),
            SizedBox(height: 24.h),
          ],

          CustomText(text: "Exercise plan details", fontWeight: FontWeight.bold, fontSize: 18.sp),
          SizedBox(height: 16.h),
          _buildLabel("Exercise plan name"),
          CustomTextField(hintText: "Enter exercise plan name", controller: _nameController),
          SizedBox(height: 16.h),
          _buildLabel("Exercise plan duration"),
          _buildDropdown(
            value: selectedDuration,
            items: durationToDays.keys.toList(),
            onChanged: (val) => setState(() {
              selectedDuration = val;
              selectedDay = 1;
            }),
          ),
          SizedBox(height: 16.h),
          _buildLabel("Exercise Level"),
          _buildDropdown(
            value: selectedLevel,
            items: ["Beginner", "Intermediate", "Advanced"],
            onChanged: (val) => setState(() => selectedLevel = val),
          ),
          SizedBox(height: 40.h),
          CustomButton(
            onPressed: () async {
              if (isAuto) {
                setState(() => _isLoading = true);
                // Simulate generation delay
                await Future.delayed(const Duration(seconds: 2));
                setState(() {
                  _isLoading = false;
                  _isAutoGenerated = true;
                });
              } else {
                setState(() => _isSecondPart = true);
              }
            },
            label: isAuto ? "Generate plan" : "Next",
          ),
        ],
      ),
    );
  }

  // --- PART 2: Manual Exercise Days & Blocks ---
  Widget _buildPartTwo() {
    return SingleChildScrollView(
      padding: EdgeInsets.all(16.r),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildDaySection(),
          SizedBox(height: 24.h),
          CustomText(text: "Exercise blocks", fontWeight: FontWeight.bold, fontSize: 16.sp),
          SizedBox(height: 12.h),
          _buildBlocksList(),
          SizedBox(height: 12.h),
          _buildDashedAddBlock(),
          SizedBox(height: 40.h),
          CustomButton(
            onPressed: () {
              Get.offAll(() => const NavBar());
            },
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Icon(Icons.fitness_center, color: Colors.white, size: 20),
                SizedBox(width: 8.w),
                CustomText(text: "Create exercise plan", color: Colors.white, fontWeight: FontWeight.bold),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // --- AUTO GENERATED RESULT (AI Insight + Blocks) ---
  Widget _buildAutoGeneratedPart() {
    return SingleChildScrollView(
      padding: EdgeInsets.all(16.r),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildAIInsightCard(),
          SizedBox(height: 24.h),
          _buildDaySection(),
          SizedBox(height: 24.h),
          CustomText(text: "Exercise blocks", fontWeight: FontWeight.bold, fontSize: 16.sp),
          SizedBox(height: 12.h),
          _buildBlocksList(),
          SizedBox(height: 40.h),
          CustomButton2(
              onTap: () {
                WidgetsBinding.instance.addPostFrameCallback((_) {
                  Get.offAll(() => const NavBar());
                });
          }, text: "Assign to client",color: Colors.orange,),
          SizedBox(height: 12.h),
          CustomButton2(
            color: Colors.grey,
            onTap: () => setState(() => _isAutoGenerated = false),
            text: "Regenerate plan",
          ),
        ],
      ),
    );
  }

  // --- UI COMPONENT HELPERS ---

  Widget _buildAIInsightCard() {
    return Container(
      padding: EdgeInsets.all(16.r),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(16.r),
        gradient: LinearGradient(
          colors: [Colors.green.withOpacity(0.1), Colors.white],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        border: Border.all(color: Colors.green.withOpacity(0.2)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.auto_awesome, color: Colors.black, size: 18),
              SizedBox(width: 8.w),
              CustomText(text: "Generated exercise", fontWeight: FontWeight.bold),
            ],
          ),
          SizedBox(height: 8.h),
          CustomText(text: "Johnson needs upper body exercise", fontSize: 13.sp),
          SizedBox(height: 12.h),
          CustomContainer(
            paddingAll: 12.r, radiusAll: 12.r, color: Colors.black.withOpacity(0.05),
            child: CustomText(
              text: "Following exercise to deduce pain and to recover. Helping to regain mobility.",
              fontSize: 12.sp,
            ),
          ),
          SizedBox(height: 12.h),
          Row(
            children: [
              CustomText(text: "Was this insight was helpful ?", fontSize: 11.sp, color: Colors.grey),
              const Spacer(),
              _buildFeedbackIcon(Icons.thumb_up_off_alt),
              SizedBox(width: 8.w),
              _buildFeedbackIcon(Icons.thumb_down_off_alt),
            ],
          )
        ],
      ),
    );
  }

  Widget _buildFeedbackIcon(IconData icon) {
    return Container(
      padding: EdgeInsets.all(4.r),
      decoration: BoxDecoration(shape: BoxShape.circle, color: Colors.black.withOpacity(0.05)),
      child: Icon(icon, size: 14, color: Colors.black54),
    );
  }

  Widget _buildDaySection() {
    int totalDays = durationToDays[selectedDuration] ?? 7;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        CustomText(text: "Exercise days", fontWeight: FontWeight.bold, fontSize: 16.sp),
        SizedBox(height: 12.h),
        SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Row(
            children: List.generate(totalDays, (index) {
              int dayNum = index + 1;
              return Padding(
                padding: EdgeInsets.only(right: 10.w),
                child: GestureDetector(
                  onTap: () => setState(() => selectedDay = dayNum),
                  child: _buildDayCircle(dayNum, selectedDay == dayNum),
                ),
              );
            }),
          ),
        ),
      ],
    );
  }

  Widget _buildBlocksList() {
    return ListView.separated(
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      itemCount: 5,
      separatorBuilder: (_, __) => SizedBox(height: 12.h),
      itemBuilder: (_, __) => _buildExerciseListItem(),
    );
  }

  Widget _buildExerciseListItem() {
    return CustomContainer(
      paddingAll: 12.r, radiusAll: 16.r, color: Colors.white,
      child: Row(
        children: [
          CustomNetworkImage(
            imageUrl: "https://picsum.photos/200",
            width: 50.w, height: 50.w, borderRadius: 8.r,
          ),
          SizedBox(width: 12.w),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                CustomText(text: "The Warm-Up", fontWeight: FontWeight.bold, fontSize: 14.sp),
                CustomText(text: "5 steps X 1 rep  •  3 minutes", fontSize: 12.sp, color: Colors.grey),
              ],
            ),
          ),
          const Icon(Icons.more_vert, color: Colors.black54),
        ],
      ),
    );
  }

  Widget _buildDayCircle(int dayNum, bool isSelected) {
    return CustomContainer(
      width: 55.w, height: 55.w, radiusAll: 30.r,
      color: isSelected ? Colors.orange : Colors.white,
      bordersColor: isSelected ? null : Colors.black.withOpacity(0.05),
      alignment: Alignment.center,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          CustomText(text: "Day", fontSize: 10.sp, color: isSelected ? Colors.white70 : Colors.grey),
          CustomText(text: "$dayNum", fontSize: 16.sp, fontWeight: FontWeight.bold, color: isSelected ? Colors.white : Colors.black),
        ],
      ),
    );
  }

  Widget _buildSwitcher() {
    return CustomContainer(
      paddingAll: 4.r, radiusAll: 30.r, color: Colors.white,
      child: Row(
        children: [
          _buildTypeTab("Manual"),
          _buildTypeTab("Auto generate"),
        ],
      ),
    );
  }

  Widget _buildTypeTab(String type) {
    bool isSelected = selectedType == type;
    return Expanded(
      child: GestureDetector(
        onTap: () => setState(() {
          selectedType = type;
          _isAutoGenerated = false; // Reset result view if switching back
        }),
        child: CustomContainer(
          paddingVertical: 12.h, radiusAll: 25.r,
          color: isSelected ? Colors.black : Colors.transparent,
          alignment: Alignment.center,
          child: CustomText(text: type, color: isSelected ? Colors.white : Colors.grey, fontWeight: FontWeight.w600),
        ),
      ),
    );
  }

  Widget _buildLabel(String text) {
    return CustomText(text: text, fontSize: 14.sp, color: Colors.grey, bottom: 6.h);
  }

  Widget _buildDropdown({String? value, required List<String> items, required Function(String?) onChanged}) {
    return Container(
      padding: EdgeInsets.symmetric(horizontal: 16.w),
      decoration: BoxDecoration(
        color: Colors.white, borderRadius: BorderRadius.circular(12.r),
        border: Border.all(color: Colors.black.withOpacity(0.05)),
      ),
      child: DropdownButtonHideUnderline(
        child: DropdownButton<String>(
          value: value, isExpanded: true,
          items: items.map((val) => DropdownMenuItem(value: val, child: Text(val))).toList(),
          onChanged: onChanged,
        ),
      ),
    );
  }

  Widget _buildDashedAddBlock() {
    return GestureDetector(
      onTap: () => Get.to(() => const AddExerciseBlockScreen()),
      child: Container(
        width: double.infinity, padding: EdgeInsets.symmetric(vertical: 24.h),
        decoration: BoxDecoration(
          color: Colors.white, borderRadius: BorderRadius.circular(16.r),
          border: Border.all(color: Colors.black12),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            CircleAvatar(backgroundColor: Colors.black.withOpacity(0.05), child: const Icon(Icons.add, color: Colors.black)),
            SizedBox(width: 12.w),
            CustomText(text: "Add Exercise block", fontWeight: FontWeight.w600),
          ],
        ),
      ),
    );
  }
}