import { startBillingReconciliation } from "./routes/clover";
import express, { type Express, type Request, type Response } from "express";
import cors from "cors";
import path from "path";
import fs from "fs";
import http from "http";
import router from "./routes";
import { handleWhopWebhook } from "./routes/whop";

const app: Express = express();

app.use(cors());

// Whop webhook — raw body preserved so we can verify signature later if needed
app.post(
  "/api/whop/webhook",
  express.raw({ type: "application/json" }),
  async (req, res) => {
    console.log("[Whop webhook] route hit, body type:", typeof req.body, req.body?.length);
    await handleWhopWebhook(req, res);
  }
);

app.use(express.json());
app.use("/screenshots", express.static(path.join(process.cwd(), "public/screenshots")));
app.use("/ebooks", express.static(path.join(process.cwd(), "public/ebooks")));
app.use(express.urlencoded({ extended: true }));

// Uploaded videos — served publicly so Meta API can fetch them
const videosUploadDir = path.resolve(process.cwd(), "uploads/videos");
if (!fs.existsSync(videosUploadDir)) fs.mkdirSync(videosUploadDir, { recursive: true });
app.use("/uploads/videos", express.static(videosUploadDir));

// Video thumbnails — generated by ffmpeg after upload
const thumbsUploadDir = path.resolve(process.cwd(), "uploads/thumbnails");
if (!fs.existsSync(thumbsUploadDir)) fs.mkdirSync(thumbsUploadDir, { recursive: true });
app.use("/uploads/thumbnails", express.static(thumbsUploadDir));

// Artifact-router readiness probe. Replit checks the registered "/api" path
// before promoting a multi-artifact deployment, so this prefix must return 200.
app.get("/api", (_req: Request, res: Response) => {
  res.status(200).json({ status: "ok", service: "api-server" });
});

app.use("/api", router);

// Serve static files — resolve relative to process.cwd() (workspace root)
// Works correctly whether run via tsx (dev) or node dist/index.cjs (prod)
const artifactsRoot = path.resolve(process.cwd(), "artifacts");
const commercialDist = path.join(artifactsRoot, "p2p-commercial/dist/web");
const websiteDist = path.join(artifactsRoot, "p2p-website/dist/public");
const universityDist = path.join(artifactsRoot, "p2c-university/dist/public");
const portalDist = path.join(artifactsRoot, "p2p-portal/dist/public");
const twmDist = path.join(artifactsRoot, "train-with-max/dist/public");

if (fs.existsSync(websiteDist)) {
  app.use("/p2p-website", express.static(websiteDist));
  app.use("/p2p-website", (_req, res) => {
    res.sendFile(path.join(websiteDist, "index.html"));
  });
}

if (fs.existsSync(universityDist)) {
  app.use("/p2c-university", express.static(universityDist));
  app.use("/p2c-university", (_req, res) => {
    res.sendFile(path.join(universityDist, "index.html"));
  });
}

if (fs.existsSync(portalDist)) {
  app.use("/p2p-portal", express.static(portalDist));
  app.use("/p2p-portal", (_req, res) => {
    res.sendFile(path.join(portalDist, "index.html"));
  });
}

if (fs.existsSync(twmDist)) {
  app.use("/train-with-max", express.static(twmDist));
  app.use("/train-with-max", (_req, res) => {
    res.sendFile(path.join(twmDist, "index.html"));
  });
}

// Root redirect — send bare domain to the main website
app.get("/", (_req, res) => res.redirect(301, "/p2p-website/"));

// Catch-all for any unknown path — redirect to main website, preserving the path
// so that p2pfitechai.com/terms → /p2p-website/terms (SPA router handles it)
app.use((req, res) => res.redirect(302, "/p2p-website" + req.path));

startBillingReconciliation();

export default app;
